apiVersion: v1
kind: Secret
metadata:
  name: {{ include "novu.fullname" . }}-secret
  labels:
    {{- include "novu.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.env.mongoInitdbRootUsername | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.env.mongoInitdbRootPassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.env.redisPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.env.jwtSecret | b64enc | quote }}
  STORE_ENCRYPTION_KEY: {{ .Values.env.storeEncryptionKey | b64enc | quote }}
  NOVU_SECRET_KEY: {{ .Values.env.novuSecretKey | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.awsSecretAccessKey | b64enc | quote }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.env.newRelicLicenseKey | b64enc | quote }}
